Migrate to Vitest for unit testing
true-myth/true-myth pull request #530
Opened 2023-04-02 20:17 UTC by jm4rtinez

This PR removes Jest and integrates Vitest for writing and running unit tests. The Vitest c8 integration is used to collect and report test coverage. As expected, it's pretty darn fast!

The `yarn test` command will run Vitest once with coverage enabled, and `yarn tdd` will start Vitest in watch mode. The Jest configuration in package.json and the `paths` option in the root-level tsconfig.json have been removed, as Vitest relies solely on ESM imports.

All imports in the test files now use Node16 module resolution. The `describe`, `expect`, and `test` functions are imported from Vitest and do not rely on globals. There is no direct drop-in equivalent for the `fail` function from Jest, but Vitest exposes the `expect.fail` function with equivalent functionality.

We also use the provided `expectTypeOf` function provided by Vitest and remove our dependency on expect-type. It looks like Vitest exposes the type-checking utilities from expect-type itself, so the API and behavior should be identical.

The CI test workflow now runs Vitest for all jobs.

Resolves #526

2023-04-03 15:11 UTC, chriskrycho requested changes
This looks great overall – thank you!

One change we need to make, though: it's actually quite important that we test the public API here (as we've had regressions when we *didn't*!). There are two basic ways we can do that:

1. We can do as we did previously, and map the imports to match their public import location. This is *less* preferable, but may be the quickest path forward unless/until we *also* tweak the build.

2. I *think* we can set up the test config to import from a built set of assets using `pretest`. This might be a larger lift if we want to keep the speed up, though, since as it stands it's going to need to re-run `tsc` (potentially with `--build` at least). 🤔 

However we tackle it, it's essential that we *not* import from the private internal paths!

2023-04-03 22:50 UTC, jm4rtinez commented
> 1. We can do as we did previously, and map the imports to match their public import location. This is less preferable, but may be the quickest path forward unless/until we also tweak the build.

After some poking around, it looks like this is achievable using the [`alias` option](https://vitest.dev/config/#alias). So in vitest.config.ts, we would add something like:

```ts
alias: {
  'true-myth': path.resolve(__dirname, './src/public'),
},
```

Then in our tests, we could import like:

```ts
import { Maybe } from 'true-myth/maybe';
import { Result } from 'true-myth/result';
```

I think this is on par with what Jest was doing before -- I'm not super familiar with Jest though, so please let me know if I have the wrong idea here. However, I think we still have the same issue: we're not _truly_ testing the distributed consumer-facing API. We're just aliasing imports from the source files nonetheless.

> 2. I think we can set up the test config to import from a built set of assets using pretest. This might be a larger lift if we want to keep the speed up, though, since as it stands it's going to need to re-run tsc (potentially with --build at least). 🤔

If we're looking to really test against the API that's visible to consumers of the library and assert the correctness of the package.json `exports` fields and the package's exports, I'm pretty sure we would need to:

1. build with `tsc`
2. prepare the package distribution with `yarn pack` or equivalent
3. install the package (or maybe link to it?)
4. make sure we resolve the imports in the test files to exports in the package
5. run the tests

It's probably doable, but wait times are gonna be rough. 

If we want to test against the _built_ code, but not necessarily the _distributed_ code, we could omit steps 2-4 above and change the `alias` option in vitest.config.ts to resolve imports to the `dist` directory contents instead. This is pretty much plug and play for the non-watch test runs, but like you mentioned, it's going to require a build before every run. Also, I couldn't get Vitest's watch mode working with this strategy. I tried to be clever and fire up tsc's watch and incremental build mode in one terminal, and Vitest's watch mode in another, but Vitest would not pick up on changes to files in the `dist` directory for me.

Whether we go with the "build, package, and test" strategy or the "build and test" strategy, there's still an elephant in the room here: we'd be looking at a slower test feedback cycle than we had with Jest! Ultimately, I think these approaches would be better suited for a CI workflow than as the "default" test behavior. These features could certainly be implemented as a follow-up to this PR.

If we do want to go this route, then I think using aliased imports in the test files (option 1) has a lot of merit. Because then, we can potentially use different Vitest configs with different `alias` options that will resolve the test imports how we want. And locally, we'll still have a fast test feedback cycle.

Let me know what you think!

2023-04-04 19:53 UTC, chriskrycho commented
Thanks for doing the digging! That summary makes a lot of sense and isn't *too* surprising. I think the path forward here I would prefer is to go ahead and use the `alias`-ing: it's technically not using the public API *exactly* as it would be when published, but given the publish step genuinely just dumps `src` into `dist`, I think that's fine for now.

At some later point it may make sense to further move this over to using Vite/SWC/etc. for the actual *transpilation* part, with `tsc` running out of band for the type checking and type definition emit, though even that is… finicky… given that ultimately we would need to invoke `tsc` for the type emit to make the type tests work. 🤔

Not a blocker for this, though! `alias` away!

2023-04-22 19:10 UTC, jm4rtinez commented
> Not a blocker for this, though! alias away!

Okay, will do! Just pushed an update to add back the aliases.

Also, there is one more topic of consideration I wanted to get your input on to close out this PR. Vitest operates independently of tsc and does not perform any type checking as part of transpilation. Currently, types are only checked during builds and also via the language service of the IDE. However, this strategy only uses the TypeScript version installed in the development environment. This means we're not getting all of the type-correctness assurances for all versions of TypeScript the library declares support for.

My recommendation here is to run `tsc --noEmit` alongside Vitest in the CI workflows, and perhaps locally as well. This will ensure our types are compatible with all TypeScript versions in the library's supported range and prevent the possibility of introducing type-level regressions.

Also, it seems we'll have to run `tsc` with the `--skipLibCheck` flag. There are some files within the Vite library source code that don't play nicely with Node16 module resolution and will trigger some type errors if the flag is not set. There's an [issue](https://github.com/vitejs/vite/issues/11552) open in Vite to track this and hopefully we can do away with `--skipLibCheck` soon.

My question for you:

Would you like to check types _automatically_ as part of the __local__ `yarn test` workflow, or have a separate script that can be run independently? Enforcing a type check before unit tests can provide an extra sanity check, but will sacrifice a little performance.

Let me know your thoughts.

2023-05-03 01:17 UTC, chriskrycho commented
Thanks

2023-05-03 01:22 UTC, chriskrycho commented
Whoops! Accidentally closed this!

Getting at your actual questions here: I agree with your recommendation overall (and use it extensively elsewhere; it only hasn't come up here b/c of how Jest was configured previously).

My general approach to these kinds of things is to have subcommands like `yarn type-check` and `yarn test`. That lets them proceed in parallel in CI, etc.; that's also useful given that we really don't need to run the runtime tests against multiple TS versions—*only* the type checking side needs to do that. Similarly, when testing locally, we can have the `tsconfig.json` include the tests so that `tsc --watch` does the right thing, while still having the separate config for publishing (just as the project already does).

Net, `yarn test` should *not* include type-checking; folks (mostly, though not only, @bmakuh and me!) working on it can easily run `yarn test` in one terminal tab and `tsc --watch --noEmit` in another!

Thanks for continuing to drive this forward!

2023-06-04 20:56 UTC, jm4rtinez commented
No worries! 

To wrap things up, this commit introduces the `yarn type-check` command that runs independently of Vitest. The `yarn type-check` command is also used in place of `yarn test` in the CI TypeScript test matrix.

Thanks for your patience, work has been crazy lately! Let me know if there's anything else you'd like to change here.

2023-06-30 22:46 UTC, chriskrycho commented
Thanks again! Will try to give this some attention and get it merged sometime in July!

2023-07-09 19:06 UTC, chriskrycho commented on tsconfig.json
> +      "true-myth/*": ["./src/public/*.ts"]
Wild; how was this even working before?!? 😂

2023-07-09 19:07 UTC, chriskrycho approved these changes
This looks great! I'm going to merge `main` into it, make sure everything is still ✅ (no reason it shouldn't be) and land it. Thanks again!

2023-07-09 19:26 UTC, merged